### ISSUE TITLE
Test data unavailable

### ISSUE THREAD

**Issue by canbooo** [microsoft/tf2-gnn#35]
Linked data for the test case in README.md does not seem to be available at

https://s3.us-east-2.amazonaws.com/dgl.ai/dataset/ppi.zip

**Comment by MarekPokropinski** [comment]
I think the dataset can be downloaded from https://data.dgl.ai/dataset/ppi.zip.
Someone please validate if data from this link works.

**Comment by zhuyuecai** [comment]
The data set from @MarekPokropinski  works for master branch

**Comment by NipunaChhabra** [comment]
In the train_graph.json, there is "multigraph":"false"? But there are clearly 20 graphs, and the train_graph_id.npy file is also used, so why is this there, should my dataset also have these variables?
