### ISSUE TITLE
Performance issu in the definition of calculate_type_to_num_incoming_edges, tf2_gnn/layers/message_passing/message_passing.py(P1))

### ISSUE THREAD

**Issue by DLPerf** [microsoft/tf2-gnn#51]
Hello, I found a performance issue in the definition of` calculate_type_to_num_incoming_edges`, tf2_gnn/layers/message_passing/message_passing.py, [`tf.shape(node_embeddings)[0]`](https://github.com/microsoft/tf2-gnn/blob/182eb6b337cecf1f0d6dce237a4a8ff4e5599e67/tf2_gnn/layers/message_passing/message_passing.py#L259) will be calculated repeatedly during the program execution, resulting in reduced efficiency. I think it should be created before the loop.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by mmjb** [comment]
This is not a noticable performance issue anyway, and should be taken care of by the TF2 graph compilation.
